(()=>{const sub=document.querySelector('#subpage');if(!sub)return;
const items=[
['Sensor Intelligence Report - BFSI - October 1, 2026','感測器情報報告－銀行、金融服務與保險業－2026 年 10 月 1 日',['VULNERABILITY','REPORT','EXPLOIT','GSIR'],''],
['Sensor Intelligence Report - Global - October 1, 2026','感測器情報報告－全球－2026 年 10 月 1 日',['VULNERABILITY','REPORT','EXPLOIT','GSIR'],''],
['China-Nexus Actor Deploys Antino Backdoor Against Asian Governments','中國關聯威脅行為者利用 Antino 後門攻擊亞洲政府機構',['APT','CHINA-NEXUS','SOCIAL ENGINEERING','LOTS'],'🇨🇳 🇹🇭 🇮🇳 🇹🇼　+4'],
['Custom GPTs Abused to Distribute Multi-Stage RAT via ClickFix','自訂 GPT 遭濫用，透過 ClickFix 散布多階段遠端存取木馬',['RAT','DLL SIDELOADING','CLICKFIX','GPT'],''],
['Critical Authentication Bypass Observed in Enterprise VPN Gateways','企業 VPN 閘道器發現嚴重身分驗證繞過漏洞',['VULNERABILITY','VPN','AUTHENTICATION','EXPLOIT'],''],
['Cloud Credential Exposure Campaign Targets Developer Environments','雲端憑證曝險活動鎖定開發人員環境',['CLOUD','CREDENTIALS','DEVELOPER','EXPOSURE'],'🌐'],
['New Ransomware Campaign Exploits Public-Facing Applications','新型勒索軟體活動利用對外公開應用程式發動攻擊',['RANSOMWARE','EXPLOIT','INITIAL ACCESS','REPORT'],''],
['Phishing Infrastructure Mimics Financial Service Login Portals','釣魚基礎設施仿冒金融服務登入入口網站',['PHISHING','BRAND ABUSE','CREDENTIALS','SOCIAL ENGINEERING'],''],
['Threat Actors Abuse Trusted Cloud Services for Malware Delivery','威脅行為者濫用可信任雲端服務散布惡意程式',['MALWARE','CLOUD','LOTS','DELIVERY'],''],
['Monthly Vulnerability Intelligence Roundup - September 2026','2026 年 9 月弱點情資月度彙整',['VULNERABILITY','CVE','REPORT','MONTHLY'],'']];
const filters={Severity:['Critical','High','Medium','Low'],Countries:['China','Thailand','India','Taiwan'],Regions:['APAC','Europe','North America','Middle East'],Industries:['BFSI','Technology','Government','Healthcare'],Vulnerabilities:['Vulnerability','Exploit','Zero-Day'], 'Custom Tags':['APT','RAT','GSIR','ClickFix']};
function render(){let grid=sub.querySelector('.subpage-grid, .advisories-page, .alerts-insights-page, .operational-page');if(!grid)return;sub.querySelector('.subpage-head').innerHTML='';grid.className='subpage-grid advisories-page';grid.innerHTML=`<div class="adv-head"><div><h1>Cyble Advisories（Cyble 安全公告） <button class="adv-help">?</button></h1><p>Intelligence reports and threat advisories published by Cyble.（Cyble 發布的情報報告與威脅公告。）</p><div class="adv-help-pop">Cyble advisories contain timely information regarding security concerns, vulnerabilities, exploits, and daily cyber threats and attacks. It is essential to keep an eye on this section to make sure every significant advisory is noticed. One can access our repository of advisories, information sheets, technical reports, and operational risk notices listed below by browsing or searching.<a>↗ Visit Help Center（前往說明中心）</a></div></div><div class="adv-tools"><label>⌕ <input placeholder="Search advisories...（搜尋公告）"></label><button>▣ Select Duration（選擇期間）⌄</button><button>▣ All Feed（所有來源）⌄</button><button class="blue">☷</button><button>↶</button><button>⋮</button></div></div><div class="adv-filterbar">${Object.keys(filters).map(k=>`<div class="adv-filter"><button>${k}⌄</button><div class="adv-menu"><input placeholder="Search...（搜尋）">${filters[k].map(v=>`<label><input type="checkbox"> ${v}</label>`).join('')}</div></div>`).join('')}<div class="adv-filter exclusive"><button>Exclusive: <b>All Advisories</b>⌄</button><div class="adv-menu"><label class="chosen">All Advisories　✓</label><label>Exclusive Only</label><label>Not Exclusive</label></div></div></div><div class="adv-list">${items.map(x=>`<article><i></i><div><h3>${x[0]}<small>（${x[1]}）</small></h3><p>Published On 01 Oct 2026　 Published By Cyble　 <b>PUBLISHED</b></p><div>${x[2].map(t=>`<span>${t}</span>`).join('')}</div></div><em>HIGH</em><small>${x[3]||'◎'}</small></article>`).join('')}</div>`;
bind();}
function bind(){document.querySelector('.adv-help')?.addEventListener('click',e=>{e.stopPropagation();document.querySelector('.adv-help-pop').classList.toggle('show')});document.querySelectorAll('.adv-filter>button').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const m=b.nextElementSibling;document.querySelectorAll('.adv-menu').forEach(x=>{if(x!==m)x.classList.remove('show')});m.classList.toggle('show')}));document.addEventListener('click',()=>document.querySelectorAll('.adv-menu,.adv-help-pop').forEach(x=>x.classList.remove('show')),{once:true});}
window.addEventListener('cyble:route',e=>{if(e.detail.page==='advisories')render()});const p=new URLSearchParams(location.search);if(p.get('page')==='advisories')render();})();
