(()=>{const sub=document.querySelector('#subpage');if(!sub)return;
const items=[
['Sensor Intelligence Report - BFSI - October 1, 2026',['VULNERABILITY','REPORT','EXPLOIT','GSIR'],''],
['Sensor Intelligence Report - Global - October 1, 2026',['VULNERABILITY','REPORT','EXPLOIT','GSIR'],''],
['China-Nexus Actor Deploys Antino Backdoor Against Asian Governments',['APT','CHINA-NEXUS','SOCIAL ENGINEERING','LOTS'],'🇨🇳 🇹🇭 🇮🇳 🇹🇼　+4'],
['Custom GPTs Abused to Distribute Multi-Stage RAT via ClickFix',['RAT','DLL SIDELOADING','CLICKFIX','GPT'],'']];
const filters={Severity:['Critical','High','Medium','Low'],Countries:['China','Thailand','India','Taiwan'],Regions:['APAC','Europe','North America','Middle East'],Industries:['BFSI','Technology','Government','Healthcare'],Vulnerabilities:['Vulnerability','Exploit','Zero-Day'], 'Custom Tags':['APT','RAT','GSIR','ClickFix']};
function render(){let grid=sub.querySelector('.subpage-grid, .advisories-page, .alerts-insights-page, .operational-page');if(!grid)return;sub.querySelector('.subpage-head').innerHTML='';grid.className='subpage-grid advisories-page';grid.innerHTML=`<div class="adv-head"><div><h1>Cyble Advisories（Cyble 安全公告） <button class="adv-help">?</button></h1><p>Intelligence reports and threat advisories published by Cyble.（Cyble 發布的情報報告與威脅公告。）</p><div class="adv-help-pop">Cyble advisories contain timely information regarding security concerns, vulnerabilities, exploits, and daily cyber threats and attacks. It is essential to keep an eye on this section to make sure every significant advisory is noticed. One can access our repository of advisories, information sheets, technical reports, and operational risk notices listed below by browsing or searching.<a>↗ Visit Help Center（前往說明中心）</a></div></div><div class="adv-tools"><label>⌕ <input placeholder="Search advisories...（搜尋公告）"></label><button>▣ Select Duration（選擇期間）⌄</button><button>▣ All Feed（所有來源）⌄</button><button class="blue">☷</button><button>↶</button><button>⋮</button></div></div><div class="adv-filterbar">${Object.keys(filters).map(k=>`<div class="adv-filter"><button>${k}⌄</button><div class="adv-menu"><input placeholder="Search...（搜尋）">${filters[k].map(v=>`<label><input type="checkbox"> ${v}</label>`).join('')}</div></div>`).join('')}<div class="adv-filter exclusive"><button>Exclusive: <b>All Advisories</b>⌄</button><div class="adv-menu"><label class="chosen">All Advisories　✓</label><label>Exclusive Only</label><label>Not Exclusive</label></div></div></div><div class="adv-list">${items.map(x=>`<article><i></i><div><h3>${x[0]}</h3><p>Published On 01 Oct 2026　 Published By Cyble　 <b>PUBLISHED</b></p><div>${x[1].map(t=>`<span>${t}</span>`).join('')}</div></div><em>HIGH</em><small>${x[2]||'◎'}</small></article>`).join('')}</div>`;
bind();}
function bind(){document.querySelector('.adv-help')?.addEventListener('click',e=>{e.stopPropagation();document.querySelector('.adv-help-pop').classList.toggle('show')});document.querySelectorAll('.adv-filter>button').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const m=b.nextElementSibling;document.querySelectorAll('.adv-menu').forEach(x=>{if(x!==m)x.classList.remove('show')});m.classList.toggle('show')}));document.addEventListener('click',()=>document.querySelectorAll('.adv-menu,.adv-help-pop').forEach(x=>x.classList.remove('show')),{once:true});}
window.addEventListener('cyble:route',e=>{if(e.detail.page==='advisories')render()});const p=new URLSearchParams(location.search);if(p.get('page')==='advisories')render();})();
