(()=>{const sub=document.querySelector('#subpage');if(!sub)return;
const alerts=[
['Edge_0_81273451.txt','CREDIT CARD NUMBER（信用卡號）','+4'],
['Firefox_0_82374190.txt','PROBABLE PASSWORD（可能為密碼）','+1'],
['Edge_0_61724538.txt','IP ADDRESS（IP 位址）','+3'],
['Edge_0_61724538.txt','IP ADDRESS（IP 位址）','+3'],
['Chrome_0_91482631.txt','DRIVING LICENSE（駕照）','+2']];
const stats=[['VIEWED（已檢視）','9'],['UNREVIEWED（未檢視）','103'],['CONFIRMED INCIDENT（已確認事件）','0'],['UNDER REVIEW（審查中）','1'],['REMEDIATION IN PROGRESS（修復進行中）','0'],['REMEDIATION NOT REQUIRED（無需修復）','0'],['RESOLVED（已解決）','2'],['FALSE POSITIVE（誤判）','1'],['INFORMATIONAL（資訊）','0']];
function spark(color='blue'){return `<svg viewBox="0 0 220 45" preserveAspectRatio="none"><polyline points="0,36 15,34 28,35 42,34 58,35 70,32 82,16 90,34 108,31 122,34 140,35 155,34 172,35 188,31 205,34 220,35" fill="none" stroke="${color==='red'?'#ff6680':'#438cf3'}" stroke-width="2"/></svg>`}
function render(){const grid=sub.querySelector('.subpage-grid, .compromised-files-page, .compromised-cards-page, .cybercrime-page, .darkweb-page');if(!grid)return;sub.querySelector('.subpage-head').innerHTML='';grid.className='subpage-grid compromised-files-page';grid.innerHTML=`<div class="cf-head"><div><h1>Compromised Files（遭入侵檔案）</h1><p>Monitor exposure of compromised files and documents found on the dark web（監控暗網中遭入侵檔案與文件的曝險）</p></div><div class="cf-tools"><button>▣ Last 30 Days（過去 30 天）⌄</button><button>◇ Keywords（關鍵字）⌄</button><button>↻</button><button>✎ Customize（自訂）</button></div></div>
<div class="cf-kpis"><article><h3>◎ TOTAL FILE EXPOSURES（檔案總曝險）　›</h3><div><strong>112</strong>${spark()}</div></article><article><h3>⚠ HIGH-RISK FILES（高風險檔案）　›</h3><div><strong class="danger">49</strong>${spark('red')}</div></article></div>
<div class="cf-mid"><section class="cf-card cf-trend"><header><h2>File Exposure Trend（檔案曝險趨勢）</h2><span>02 Sept - 02 Oct 2026</span></header><div class="cf-chart"><svg viewBox="0 0 900 430" preserveAspectRatio="none"><g stroke="#282b32" stroke-dasharray="4 4"><line x1="50" y1="40" x2="870" y2="40"/><line x1="50" y1="145" x2="870" y2="145"/><line x1="50" y1="250" x2="870" y2="250"/><line x1="50" y1="370" x2="870" y2="370"/></g><path d="M50 185 C120 320 170 365 245 365 S370 85 455 90 S570 360 645 360 S770 300 865 225" fill="none" stroke="#f5b400" stroke-width="3"/><g fill="#f5b400"><circle cx="50" cy="185" r="4"/><circle cx="245" cy="365" r="4"/><circle cx="455" cy="90" r="4"/><circle cx="645" cy="360" r="4"/><circle cx="865" cy="225" r="4"/></g></svg></div><p class="cf-legend">● Compromised Files（遭入侵檔案）　112</p></section><aside class="cf-card cf-priority"><header><h2>Priority File Alerts（優先檔案警示）</h2><a>View All（查看全部） ↗</a></header>${alerts.map(a=>`<article><i>▧</i><div><b>${a[0]}</b><small>Compromised Files（遭入侵檔案） · 20h ago（20 小時前）</small><em>${a[1]}</em><span>${a[2]}</span></div><strong>HIGH（高）</strong></article>`).join('')}<button>Load more（載入更多）</button></aside></div>
<section class="cf-card cf-source"><h2>Exposure by Source（依來源分類的曝險）</h2><div class="cf-source-head"><b>SERVICE（服務）</b><b>VOLUME（數量）</b><b>SEVERITY（嚴重性）</b></div><div class="cf-source-row"><div><i>▧</i><b>Compromised Files（遭入侵檔案）</b></div><div><strong>112</strong><small>alert(s)（警示）</small>${spark()}</div><div><u><i style="width:46%"></i><b></b></u><small>49H　63M　0L</small></div><b>›</b></div></section>
<section class="cf-card cf-status"><div class="cf-status-head"><h2>Alert Status Breakdown（警示狀態分布）</h2><b>Compromised Files（遭入侵檔案）</b></div><div class="cf-status-grid">${stats.map((s,i)=>`<article><i>${['◉','◷','⚠','⌕','⚒','⊙','✓','⊗','ⓘ'][i]}</i><span>${s[0]}</span><strong>${s[1]}</strong></article>`).join('')}</div></section>`;}
window.addEventListener('cyble:route',e=>{if(e.detail.page==='compromised-files')render()});if(new URLSearchParams(location.search).get('page')==='compromised-files')render();})();
