(()=>{const sub=document.querySelector('#subpage');if(!sub)return;
const filters={
 'Sources（來源）':['AbuseIPDB - Firewall ip blocklist','Avast Threat Intel IoCs Feed','Benkow.cc','C2 intelfeedbot','CISA','CRITICAL PATH SECURITY'],
 'Types（類型）':['Domain（網域）','Email（電子郵件）','FileHash-MD5','FileHash-SHA1','FileHash-SHA256','IPv4','IPv6','URL'],
 'Confidence（可信度）':['High（高）','Medium（中）','Low（低）'],
 'Behaviour Tags（行為標籤）':['Ransomware（勒索軟體）','crawler（爬蟲）','%SMimikatzCommandsLoaded','%ZuBytes','%ZuBytesCobaltStrikeBeacon','%ZuBytesEmotetPattern'],
 'Industries（產業）':['Aerospace & Defense（航太與國防）','Agriculture & Livestock（農業與畜牧）','Automotive（汽車）','BFSI（銀行、金融服務與保險）','Chemicals（化工）','Construction（營建）'],
 'Countries（國家）':['Afghanistan（阿富汗）','Aland Islands（奧蘭群島）','Albania（阿爾巴尼亞）','Algeria（阿爾及利亞）','American Samoa（美屬薩摩亞）','Andorra（安道爾）'],
 'Regions（區域）':['Asia & Pacific (APAC)（亞太）','Australia and New Zealand (ANZ)（澳洲與紐西蘭）','Europe & UK（歐洲與英國）','Middle East & Africa (MEA)（中東與非洲）','North America (NA)（北美）','South America (SA)（南美）'],
 'Threat Actors（威脅行為者）':['NightCipher','Iron Ransom','BERT-X','313 Spectre','Northstar Locker','Blue Viper'],
 'Malware（惡意程式）':['Brow99','Immortal Stealer','Unidentified 119','X-Files Stealer','000Stealer','01flip']
};
const rows=Array.from({length:34},(_,i)=>{
 const names=['aurora-node.example','northstar-cdn.example','shadow-login.example','demo-c2.example','mirror-gateway.example','vault-sync.example','sample-mail.example','blue-viper.example'];
 const tags=['MALICIOUS（惡意）','C2','PHISHING（釣魚）'];
 return [names[i%names.length], i%4===0?'DOMAIN（網域）':'DOMAIN（網域）', ['Aug 27, 2026','Jul 03, 2026','Sep 12, 2026'][i%3], 'Oct 02, 2026', i%5===0?'Medium（中）':'High（高）', [88,93,85,91,76][i%5], i%3===0?'CISA':'Demo TIF', tags[i%tags.length], `+${(i%4)+1} More（更多）`, `${i%2} ⚡  ${i%3} ♙  ${i%2} ⌖  ${i%4} ▦`];
});
function dropdown(label,vals){return `<div class="ioc-filter"><button class="ioc-filter-btn">${label}⌄</button><div class="ioc-menu"><label>⌕ <input placeholder="Search...（搜尋）"></label>${vals.map(v=>`<button class="ioc-option"><i></i>${v}</button>`).join('')}</div></div>`}
function render(){const grid=sub.querySelector('.subpage-grid, .ioc-lookup-page, .malware-families-page');if(!grid)return;sub.querySelector('.subpage-head').innerHTML='';grid.className='subpage-grid ioc-lookup-page';grid.innerHTML=`<div class="ioc-head"><div><h1>IoC Lookup（IoC 查詢） <span class="ioc-help" tabindex="0">?<span class="ioc-help-pop">Search and analyse Indicators of Compromise<b>搜尋並分析入侵指標（Indicators of Compromise, IoC），協助辨識可疑網域、IP、檔案雜湊與其他威脅跡象。</b><a href="#">↗ Visit Help Center（前往說明中心）</a></span></span></h1><p>Search and analyse Indicators of Compromise（搜尋並分析入侵指標）</p></div><div class="ioc-tools"><label>⌕ <input placeholder="Search IoC...（搜尋 IoC）"></label><button>▣ Last 24 Hours（過去 24 小時）⌄</button><button>☷</button><button>↻</button><button>⇩</button></div></div><div class="ioc-filters">${dropdown('Sources（來源）',filters['Sources（來源）'])}${dropdown('Types（類型）',filters['Types（類型）'])}${dropdown('Confidence（可信度）',filters['Confidence（可信度）'])}<div class="ioc-filter risk"><button class="ioc-filter-btn">Risk Score（風險分數）⌄</button><div class="ioc-menu risk-menu"><b>Risk Score（風險分數） <span>0 - 100</span></b><div class="risk-line"><i></i><u></u></div><div class="risk-labels"><span>MIN</span><span>MAX</span></div><div class="risk-inputs"><input value="0"><em>to</em><input value="100"></div></div></div>${dropdown('Behaviour Tags（行為標籤）',filters['Behaviour Tags（行為標籤）'])}${dropdown('Industries（產業）',filters['Industries（產業）'])}${dropdown('Countries（國家）',filters['Countries（國家）'])}${dropdown('Regions（區域）',filters['Regions（區域）'])}${dropdown('Threat Actors（威脅行為者）',filters['Threat Actors（威脅行為者）'])}${dropdown('Malware（惡意程式）',filters['Malware（惡意程式）'])}<span>Total（總數）：<b>2,684,930</b></span></div><div class="ioc-kpis"><article><strong>2,468,320</strong><b>Domains（網域）</b><span>Domains & URL（網域與 URL）</span><i>◎</i></article><article><strong>216,104</strong><b>IPs</b><span>IPv4 & IPv6</span><i>⌖</i></article><article><strong>82</strong><b>File Hashes（檔案雜湊）</b><span>MD5, SHA1 & SHA256</span><i>▧</i></article><article><strong>24</strong><b>Others（其他）</b><span>Email & Wallet Address（電子郵件與錢包位址）</span><i>•••</i></article></div><section class="ioc-table-shell"><div class="ioc-table-wrap"><table><thead><tr><th>IOC</th><th>FIRST SEEN（首次發現）</th><th>LAST SEEN（最後發現）</th><th>CONFIDENCE RATING（可信度）</th><th>RISK SCORE（風險分數）</th><th>SOURCES（來源）</th><th>BEHAVIOUR TAGS（行為標籤）</th><th>RELATED ENTITIES（關聯實體）</th></tr></thead><tbody>${rows.map(r=>`<tr><td><a>◎ ${r[0]}</a><small>${r[1]}</small></td><td>${r[2]}</td><td>${r[3]}</td><td><b class="conf ${r[4].startsWith('Medium')?'med':''}">${r[4]}</b></td><td><b class="risk-score">${r[5]}</b></td><td>${r[6]}</td><td><b class="tag">${r[7]}</b><small>${r[8]}</small></td><td>${r[9]}</td></tr>`).join('')}</tbody></table></div><footer><span>1 - 20 of 2,684,930 Record(s)（筆）</span><div><span>Items per page（每頁筆數）：</span><button>20⌄</button><button>‹ Previous（上一頁）</button><button>Next（下一頁） ›</button></div></footer></section>`;bind();}
function bind(){const fs=[...document.querySelectorAll('.ioc-filter')];fs.forEach(f=>{const b=f.querySelector('.ioc-filter-btn'),m=f.querySelector('.ioc-menu');b.addEventListener('click',e=>{e.stopPropagation();fs.forEach(o=>o!==f&&o.classList.remove('open'));f.classList.toggle('open')});const inp=f.querySelector('.ioc-menu input');if(inp)inp.addEventListener('input',()=>{const q=inp.value.toLowerCase();m.querySelectorAll('.ioc-option').forEach(o=>o.hidden=!o.textContent.toLowerCase().includes(q))})});document.addEventListener('click',e=>{if(!e.target.closest('.ioc-filter'))fs.forEach(f=>f.classList.remove('open'))});}
window.addEventListener('cyble:route',e=>{if(e.detail.page==='ioc-lookup')render()});if(new URLSearchParams(location.search).get('page')==='ioc-lookup')render();})();
