(()=>{const sub=document.querySelector('#subpage');if(!sub)return;
const companies=[['星河銀行','BANKING','APAC','BFSI',32,4,10,'31 Mar 2027'],['遠景證券','REGULAR','APAC','Financial Services',41,4,6,'18 Jul 2028'],['晨曦金融控股','REGULAR','APAC','BFSI',87,3,5,'31 May 2027'],['青岳銀行','BANKING','APAC','BFSI',21,2,5,'30 Apr 2028'],['海岳數位銀行','BANKING','APAC','BFSI',54,3,8,'30 Jun 2027'],['凌峰商業銀行','BANKING','APAC','BFSI',46,2,6,'23 Jan 2028'],['曜石科技','REGULAR','APAC','Technology',72,4,8,'14 Aug 2027'],['雲拓資訊','REGULAR','APAC','Technology',28,2,5,'09 Dec 2027'],['北辰產險','REGULAR','APAC','Insurance',64,3,6,'20 Feb 2028'],['澄海人壽','REGULAR','APAC','Insurance',39,2,5,'11 Nov 2027']];
const card=c=>`<article class="mc-company"><header><span>${c[0].slice(0,2)}</span><div><b>${c[0]}</b><small>2026</small></div><em class="${c[1].toLowerCase()}">${c[1]}</em></header><div class="mc-company-body"><div><p>Admin　<span class="avatars">AD</span></p><p>User　<span class="avatars">U1 U2 U3</span></p><p>Disabled users　-</p><p>Region　<i>${c[2]}</i></p><p>Industry　<i>${c[3]}</i></p></div><div><p>⚿　<strong>${c[4]}/100</strong> Keywords</p><p>♙　<strong>${c[5]}/${c[6]}</strong> Seats</p><p>▧　<strong>${c[1]==='REGULAR'?24:0}</strong> Executive Report Credits</p></div></div><footer>●　License Expiry: ${c[7]}</footer></article>`;
function render(){const grid=sub.querySelector('.subpage-grid, .newsfeed-page, .mssp-page');if(!grid)return;sub.querySelector('.subpage-head').innerHTML='';grid.className='subpage-grid mssp-page';grid.innerHTML=`<section class="mc-hero"><div class="mc-logo">M</div><div><h1>MSSP Insights（MSSP 洞察）　<small>?</small></h1><p>Welcome, <b>NOVA CYBER</b></p><p>Manage and monitor your entire ecosystem of child companies and subscriptions.（管理並監控所有子公司與訂閱服務。）</p><p>◎ nova-cyber.example　　▱ 64 services</p><div class="mc-hero-stats"><b><strong>24</strong>Child Companies（子公司）</b><b><strong>14</strong>Regular（一般）</b><b><strong>10</strong>Banking（銀行）</b></div></div></section>
<div class="mc-kpis"><article>⌘ <span>Keywords（關鍵字）<b>3,420 <small>/ 5,000</small></b></span></article><article>♙ <span>Users（使用者）<b>7 <small>/ 20</small></b></span></article><article>▧ <span>Executive Report Credits（高階報告額度）<b>46</b></span></article><article>▥ <span>Third-Party Credits（第三方額度）<b>3</b></span></article></div>
<div class="mc-two"><section class="mc-panel"><h2>License Status（授權狀態）</h2><div class="mc-license"><div class="mc-ring"></div><div><b>22<small>License Ongoing（授權有效）</small></b><b>1<small>Need Renewal（需要續約）</small></b><b>1<small>Expired（已到期）</small></b></div></div></section><section class="mc-panel"><h2>User Seats（使用者席次 Top 5）</h2><div class="mc-seat-chart">${[['星河銀行',4,10],['遠景證券',4,6],['晨曦金融',3,5],['青岳銀行',2,5],['海岳銀行',3,8]].map(x=>`<div><i style="height:${x[1]*15}px"></i><em style="height:${x[2]*15}px"></em><small>${x[0]}</small></div>`).join('')}</div><p class="mc-legend">■ Active Users（啟用）　 ■ Available Seats（可用席次）</p></section></div>
<section class="mc-panel mc-empty"><h2>Takedown Used（下架服務使用量 Top 5）</h2><p>No takedown data（目前無下架資料）</p></section>
<section class="mc-panel"><h2>Takedown Statuses（下架狀態）</h2><div class="mc-stack">${[['NOVA CYBER',92,15],['星河銀行',48,5],['晨曦金融',34,2],['青岳銀行',29,1],['遠景證券',18,4],['海岳銀行',12,3]].map(x=>`<p><span>${x[0]}</span><i><u style="width:${x[1]}%"></u><b style="width:${x[2]}%"></b></i></p>`).join('')}</div><p class="mc-legend">● Monitored　 ● Rejected　 ● On Hold　 ● Duplicate　 ● Closed　 ● Active　 ● New</p></section>
<section class="mc-panel mc-alert"><h2>Alert Usage（警示使用量 Top 10）</h2><div class="mc-period">▣ Last 24 Hours（過去 24 小時）⌄　↻</div><div>No alert usage data（目前無警示使用資料）</div></section>
<div class="mc-two"><section class="mc-panel"><h2>Keyword Usage（關鍵字使用量）</h2><div class="mc-donut keyword"></div><p class="mc-legend">● 星河銀行　● 遠景證券　● 晨曦金融　● 青岳銀行　● 曜石科技</p></section><section class="mc-panel"><h2>Engagement Types（合作類型）</h2><div class="mc-donut engage"></div><p class="mc-legend">● Enterprise 23　 ● Assessment/PoC 1</p></section></div>
<section class="mc-panel"><h2>Keywords Distribution Service Wise（各服務關鍵字分布）</h2><div class="mc-service-chart">${[82,8,6,4,5,2,1,0,1,3,11,48,0].map((v,i)=>`<i style="height:${v*3}px"><span>${['星河','曜石','晨曦','青岳','雲拓','北辰','凌峰','遠景','澄海','海岳','星橋','極光','新域'][i]}</span></i>`).join('')}</div><p class="mc-legend">● Darkweb and Cybercrime　 ● Threat Intelligence　 ● Brand Intelligence　 ● Attack Surface Monitoring</p></section>
<section class="mc-panel"><h2>Companies by Region（公司地區分布）</h2><div class="mc-region"><i></i><span>24</span><small>APAC</small></div></section>
<section class="mc-panel mc-child"><div class="mc-child-head"><h2>Child Companies（子公司） <small>24</small></h2><label>⌕ <input placeholder="Search companies...（搜尋公司）"></label></div><div class="mc-child-scroll">${companies.map(card).join('')}</div></section>`;}
window.addEventListener('cyble:route',e=>{if(e.detail.page==='mssp')render()});if(new URLSearchParams(location.search).get('page')==='mssp')render();})();