(()=>{const sub=document.querySelector('#subpage');if(!sub)return;
const filters={Countries:['Taiwan','Japan','Singapore','United States','Germany'],Regions:['Asia & Pacific (APAC)','Europe','North America','Middle East'],Industries:['Aerospace & Defense','Agriculture & Livestock','Automotive','Aviation','BFSI','Chemicals'],Tags:['Exfiltration Tactics','Exploit Kit','Extortion','Financial Fraud','Form Grabber','Gift Card Fraud','Hacktivism'], 'Threat Actor Types':['Affiliate','APT','Competitor / Industrial Spy','Cybercrime — Individual','Cybercrime — Organized Group','Data Broker'], 'Type of Attacks':['Brute Force / Credential Attack','Code / Command Injection','Communications Interception','Data Breach / Exfiltration','Data Leak (Unintentional)','Denial of Service (DoS/DDoS)']};
const rows=[
['NightSpecter Claims Breach of a Taiwan-based Medical Network; Patient Records Allegedly Exposed','「NightSpecter」聲稱入侵台灣某醫療網路，疑似造成病患資料外洩','28 Sept 2026','NightSpecter','AI GENERATED'],
["Hacktivist Group 'Blue Lantern' Claims to Disrupt 31 TB of Data from an Asian Manufacturing Firm",'駭客行動組織「Blue Lantern」聲稱破壞亞洲某製造企業 31 TB 資料','17 Sept 2026','Blue Lantern','VETTED'],
['72.8 MB Database Allegedly Leaked from a Taiwan-based Education Institution','台灣某教育機構疑似有 72.8 MB 資料庫遭外洩','16 Sept 2026','GreySkull','AI GENERATED'],
['418,260 Records Allegedly Stolen from a Taiwan-based Retail Warehouse Operator','台灣某零售倉儲業者疑似有 418,260 筆紀錄遭竊','15 Sept 2026','kiki8842','AI GENERATED'],
['Threat Actor Advertises Access to an APAC Financial Services Environment','威脅行為者兜售亞太地區某金融服務環境的存取權限','13 Sept 2026','VoidMarket','VETTED'],
['Ransomware Group Claims Compromise of Regional Technology Supplier','勒索軟體組織聲稱入侵某區域科技供應商','11 Sept 2026','BlackComet','AI GENERATED'],
['Credential Dump Targeting Taiwanese E-commerce Users Observed on Underground Forum','地下論壇發現疑似鎖定台灣電商使用者的憑證資料集','9 Sept 2026','OrchidFox','VETTED'],
['Data Broker Offers Corporate Email Dataset from APAC Organizations','資料仲介者兜售亞太地區企業電子郵件資料集','7 Sept 2026','DataPier','AI GENERATED']];
function render(){const grid=sub.querySelector('.subpage-grid, .newsflash-page, .advisories-page, .alerts-insights-page, .operational-page');if(!grid)return;sub.querySelector('.subpage-head').innerHTML='';grid.className='subpage-grid newsflash-page';grid.innerHTML=`<div class="nf-head"><div><h1>Cyble NewsFlash（Cyble 快訊） <button class="nf-help">?</button></h1><p>Real-time intelligence flash reports published by Cyble analysts.（由 Cyble 分析師發布的即時情報快訊。）</p><div class="nf-help-pop">Cyble NewsFlash 是由 Cyble 暗網情報分析師使用的數位情報看板，提供全球暗網網路犯罪活動的近即時通知。NewsFlash 會提供重大資安事件、異常威脅行為者／威脅組織活動，以及可能影響特定實體或組織之潛在網路攻擊或資料外洩的初步情報；部分資訊可能尚未完成驗證。<a>↗ 前往說明中心</a></div></div><div class="nf-tools"><label>⌕ <input placeholder="Search newsflash...（搜尋快訊）"></label><div class="nf-tool-menu duration"><button>▣ Select Duration（選擇期間）⌄</button><div class="nf-tool-drop">${['Today（今天）','Yesterday（昨天）','This Week（本週）','Last Week（上週）','This Month（本月）','Last Month（上個月）','Last 24 Hours（過去 24 小時）','Last 7 Days（過去 7 天）','Last 30 Days（過去 30 天）','Last 3 Months（過去 3 個月）','Last 6 Months（過去 6 個月）','Current Year（今年）','Previous Year（去年）','Custom（自訂） ›'].map(x=>`<label>${x}</label>`).join('')}</div></div><div class="nf-tool-menu feed"><button>▣ Taiwan News　×</button><div class="nf-tool-drop"><h4>PRESETS（預設）</h4><label>All Feed（全部來源）</label><label class="selected">Taiwan News（台灣新聞） <b>📌</b></label></div></div><button class="blue">☷</button><button>↶</button><button>⋮</button></div></div><div class="nf-filterbar">${Object.entries(filters).map(([k,v],i)=>`<div class="nf-filter"><button>${i<2?'<b>1</b> ':''}${k}${i<2?'　×':'　⌄'}</button><div class="nf-menu"><input placeholder="Search...（搜尋）">${v.map(x=>`<label><input type="checkbox" ${i<2&&x.startsWith(i?'Asia':'Taiwan')?'checked':''}> ${x}</label>`).join('')}</div></div>`).join('')}</div><div class="nf-list">${rows.map(r=>`<article><i></i><div><h3>${r[0]}<small>（${r[1]}）</small></h3><p>Published ${r[2]}　♙ ${r[3]}</p><span>◎　TAIWAN　·　ASIA & PACIFIC (APAC)</span></div><aside><b>UNVIEWED</b><em class="${r[4]==='VETTED'?'vetted':''}">${r[4]}</em></aside></article>`).join('')}</div><footer class="nf-pager"><span>Showing <b>1–8</b> of <b>187</b></span><div>«　‹　 Go to　<b>1</b>　of 24　›　»</div><span>Rows per page　<b>50⌄</b></span></footer>`;bind();}
function bind(){document.querySelectorAll('.nf-tool-menu>button').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const d=b.nextElementSibling;document.querySelectorAll('.nf-tool-drop').forEach(x=>x!==d&&x.classList.remove('show'));d.classList.toggle('show')}));const h=document.querySelector('.nf-help'),p=document.querySelector('.nf-help-pop');if(h&&p){h.addEventListener('mouseenter',()=>p.classList.add('show'));h.addEventListener('mouseleave',()=>setTimeout(()=>{if(!p.matches(':hover'))p.classList.remove('show')},80));p.addEventListener('mouseleave',()=>p.classList.remove('show'));}document.querySelectorAll('.nf-filter>button').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const m=b.nextElementSibling;document.querySelectorAll('.nf-menu').forEach(x=>x!==m&&x.classList.remove('show'));m.classList.toggle('show')}));}
window.addEventListener('cyble:route',e=>{if(e.detail.page==='newsflash')render()});if(new URLSearchParams(location.search).get('page')==='newsflash')render();})();
