const news=['Tinubu 外交三連勝：羅安達的尊嚴、德里的命運、紐約的正義','秘魯觀察（一）：跨國支持','1965 年與國家成熟度的考驗','今天從阿聯酋出發？以色列航班暫停，請確認阿聯酋航空、阿提哈德與杜拜航空資訊','乘客成功阻止杜拜飛往特拉維夫航班的墜機企圖','選舉利害關係人採取行動反制網路假訊息','奈及利亞獨立 66 週年，各界領袖表達不同看法','美軍撤離伊拉克後留下安全疑慮','09/30 連結（一）：以色列民眾在空中避免一場悲劇','飛往以色列的航班因機師衝突改降沙烏地阿拉伯','波斯灣石油出口恢復至戰前水準','奈及利亞資訊戰持續升溫'];
document.querySelector('.news-list').innerHTML=news.map((n,i)=>'<div><small>'+['Leadership Newspapers','Woodsmokeblog','Detiknews','Gulf News','Ariana News','Disa'][i%6]+' · 2026年10月01日</small><strong>'+n+'</strong></div>').join('');
const orgs=[['星河科技',57,'B','+7.0'],['晨星商銀',52,'B','+2.0'],['遠景人壽',41,'B','-1.0'],['藍海金控',34,'B','+3.0'],['雲峰資訊',27,'A','-1.0'],['曙光證券',24,'A','-2.0'],['新辰金控',22,'A','+1.0'],['天際證券',20,'A','+3.0'],['森岳商銀',18,'A','-2.0'],['東川企銀',17,'A','+2.0'],['極光銀行',15,'A','-9.0'],['晨露餐飲',14,'A','+1.0'],['海岳銀行',12,'A','-5.0'],['安曜產險',9,'A','-2.0'],['星瀚人壽',8,'A','-1.0'],['青岳人壽',7,'A','+1.0']];
document.querySelector('.org-grid').innerHTML=orgs.map(o=>'<div class="org '+(o[2]=='B'?'b':'')+'"><div class="mini">'+o[2]+'</div><div><strong>'+o[0]+'</strong><p>'+o[1]+' <small>/100</small></p></div><small>'+o[3]+'</small></div>').join('');
const flash=['MontanaTrue 尋求大量購買德國分類廣告平台 Kleinanzeigen.de 的已註冊電子郵件帳號','尼泊爾數位錢包公司 HamroPay 疑遭竊超過 37.3 萬筆身分與金融資料，並被公開兜售','阿根廷衛生部與 RENAPER 的受益人個資疑遭竊並被兜售','南韓電商平台 Metree 疑遭竊超過 100 萬筆客戶資料並被兜售'];
const cyber=['FBI「Blackout 行動」瓦解鎖定美國人的海外詐騙集團','網際網路協會推出全球線上信任與安全中心，作為更安全網路倡議的一環','司法機關被促加速審理貪腐案件','烏茲別克與新加坡 Group-IB 簽署資安合作備忘錄','Apple CoreGraphics 概念驗證程式出現，WhatsApp PDF 檢查顯示可能的攻擊傳遞途徑'];
document.querySelector('#flash').innerHTML=flash.map(x=>'<div>'+x+'<small>▰　零售業　· 10 小時前</small></div>').join('');
document.querySelector('#cyber').innerHTML=cyber.map(x=>'<div>'+x+'<small>資安新聞來源 · 1 小時前</small></div>').join('');
document.querySelector('.bar-chart').innerHTML=[66,73,61,82,79,91,8].map(h=>'<div style="height:'+h+'%"></div>').join('');
