(()=>{const sub=document.querySelector('#subpage');if(!sub)return;
const fileRows=[
['demo-sample-01.bin','Windows（Windows）','Failed（失敗）','-','-','15 Oct 2025','-'],
['demo-loader-2024.exe','Windows（Windows）','Failed（失敗）','Malicious（惡意）','9.6','14 Nov 2024','Alex Chen'],
['office-macro-demo.docm','Windows（Windows）','Completed（完成）','Suspicious（可疑）','7.4','02 Oct 2026','Demo Analyst'],
['archive-test.zip','Windows（Windows）','Completed（完成）','Benign（良性）','1.2','01 Oct 2026','Demo Analyst']
];
const urlRows=[
['https://sample-alpha.example','Windows（Windows）','Failed（失敗）','Benign（良性）','0.0','11 Dec 2024','Alex Chen'],
['https://portal-demo.example/login','Windows（Windows）','Failed（失敗）','Benign（良性）','0.0','06 Dec 2024','Alex Chen'],
['https://safe-check.example/','Windows（Windows）','Completed（完成）','Benign（良性）','1.0','06 Oct 2024','Demo Analyst'],
['https://url-test.example','Windows（Windows）','Completed（完成）','Benign（良性）','1.0','06 Oct 2024','Demo Analyst']
];
function table(kind,rows){const first=kind==='file'?'FILE NAME（檔案名稱）':'URL';return `<section class="tl-table-shell"><div class="tl-table-wrap"><table><thead><tr><th>${first}</th><th>PLATFORM（平台）</th><th>STATUS（狀態）</th><th>CLASSIFIED AS（分類結果）</th><th>Risk Score（風險分數） ⇅</th><th>Date（日期） ⇅</th><th>UPLOADED BY（上傳者）</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td>▣ ${r[1]}</td><td><b class="tl-status ${r[2].startsWith('Completed')?'ok':'bad'}">${r[2]}</b></td><td>${r[3]==='-'?'-':`<b class="tl-class ${r[3].startsWith('Benign')?'ok':r[3].startsWith('Suspicious')?'warn':'bad'}">${r[3]}</b>`}</td><td>${r[4]==='-'?'-':`<b class="tl-risk ${Number(r[4])<3?'ok':Number(r[4])<8?'warn':'bad'}">${r[4]}</b>`}</td><td>${r[5]}</td><td>${r[6]}</td></tr>`).join('')}</tbody></table></div><footer><span>Showing（顯示） 1-${rows.length} of ${rows.length}</span><div>«　‹　Go to（前往） <button>1</button> of 1　›　»</div><div>Rows per page（每頁列數） <button>10⌄</button></div></footer></section>`}
function render(){const grid=sub.querySelector('.subpage-grid, .threat-lens-page, .ransomware-extortion-page');if(!grid)return;sub.querySelector('.subpage-head').innerHTML='';grid.className='subpage-grid threat-lens-page';grid.innerHTML=`<div class="tl-head"><div><h1>Threat Lens（威脅分析） <span class="tl-help" tabindex="0">?<span class="tl-help-pop">Submit files and URLs for dynamic and static malware analysis<b>提交檔案與 URL，進行動態與靜態惡意程式分析。</b><a href="#">↗ Visit Help Center（前往說明中心）</a></span></span></h1><p>Submit files and URLs for dynamic and static malware analysis（提交檔案與 URL 進行動態與靜態惡意程式分析）</p></div><div class="tl-daily">◔ Daily Scans（每日掃描） <b>0/1</b></div></div><div class="tl-tabs"><button class="active" data-tab="file">File（檔案）</button><button data-tab="url">URL</button></div><section class="tl-file"><div class="tl-toolbar"><div></div><div><label>⌕ <input placeholder="Search（搜尋）"></label><button>▣ Select Duration（選擇期間）⌄</button><button>☷</button><button>↻</button><button>＋ Upload File（上傳檔案）</button><button>⇩</button></div></div>${table('file',fileRows)}</section><section class="tl-url" hidden><div class="tl-toolbar"><div></div><div><label>⌕ <input placeholder="Search（搜尋）"></label><button>▣ Select Duration（選擇期間）⌄</button><button>☷</button><button>↻</button><button>＋ Submit URL（提交 URL）</button><button>⇩</button></div></div>${table('url',urlRows)}</section>`;bind();}
function bind(){const tabs=[...document.querySelectorAll('.tl-tabs button')],file=document.querySelector('.tl-file'),url=document.querySelector('.tl-url');const sw=t=>{const isUrl=t==='url';tabs.forEach(x=>x.classList.toggle('active',x.dataset.tab===t));file.hidden=isUrl;url.hidden=!isUrl;file.style.display=isUrl?'none':'block';url.style.display=isUrl?'block':'none';};tabs.forEach(b=>b.addEventListener('click',()=>sw(b.dataset.tab)));sw('file');}
window.addEventListener('cyble:route',e=>{if(e.detail.page==='threat-lens')render()});if(new URLSearchParams(location.search).get('page')==='threat-lens')render();})();
